token: ddLoBHn9aMs9fWPt7DsSKOFM
consumer_key: QfZXrnSiHT094MO2tKwSzWO9l
consumer_secret: VsNAkiw1TTOrBDOokXWDQBO3Iu3I6Ry3PIu515iB8u1XUS4xuc
access_token: 3309892394-hdmLV7eEF2CUHSrSc4WvzDzO5eavagZckpVtu0l
access_token_secret: liTRRf6hKQdyeeSYAIxgYGJpbKy6YScMkcErsncYcz0Cw
reply_text: Slackに招集がかかりました。見に来てね。 https://kstm-su.slack.com/messages/
slack_text: 招集かけます！！
